services:
  pg:
    image: bitnami/postgresql:latest
    container_name: pg
    restart: unless-stopped
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
      - db:/bitnami/postgresql
    networks:
      - db
      - widget

  app:
    build: .
    depends_on:
      - pg
    container_name: upload-widget-server
    restart: unless-stopped
    ports:
      - $PORT:$PORT
    environment:
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL
    networks:
      - widget

volumes:
  db:
    driver: local
networks:
  widget:
    driver: bridge
  db:
    driver: bridge
